package com.example.engine

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.net.Uri
import android.os.Environment
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.model.BmpFormat
import com.example.model.JacquardDesign
import java.io.File
import java.io.FileOutputStream

object ShareManager {

    /**
     * Builds standard technical specification sheet text for WhatsApp and textile records
     */
    fun buildSpecText(design: JacquardDesign): String {
        val cfg = design.config
        val paletteLines = design.palette.joinToString("\n") { yarn ->
            "  • [${yarn.id + 1}] ${yarn.name} (${yarn.hexCode}): ${"%.1f".format(yarn.percentage)}% | Weave: ${yarn.assignedWeave.labelEn}"
        }

        return """
🧵 *JACQUARD DESIGN SPECIFICATION* 🧵
━━━━━━━━━━━━━━━━━━━━
📌 *Design Name:* ${design.title}
📐 *Loom Matrix:*
  • Warp Hooks (ताना): ${design.widthHooks} ends
  • Weft Picks (बाना): ${design.heightPicks} picks
  • Total Weaving Points: ${design.widthHooks * design.heightPicks} pts
📊 *Fabric Density & Dimensions:*
  • Loom EPI (Ends/inch): ${cfg.epi}
  • Loom PPI (Picks/inch): ${cfg.ppi}
  • Fabric Size: ${"%.1f".format(cfg.widthCm)} × ${"%.1f".format(cfg.heightCm)} cm (${"%.2f".format(cfg.widthInches)}" × ${"%.2f".format(cfg.heightInches)}")
🎨 *Color Palette (${design.palette.size} Colors):*
$paletteLines
💾 *Format:* ${cfg.bmpFormat.label} (Windows BMP)
━━━━━━━━━━━━━━━━━━━━
Generated by Jacquard Studio CAD
        """.trimIndent()
    }

    /**
     * Exports BMP file to cache and shares directly via WhatsApp (or chooser if not installed)
     */
    fun shareBmpToWhatsApp(context: Context, design: JacquardDesign, bmpFormat: BmpFormat = design.config.bmpFormat) {
        try {
            val fileName = "${sanitizeFilename(design.title)}_${design.widthHooks}x${design.heightPicks}.bmp"
            val cacheDir = File(context.cacheDir, "shared_files").apply { mkdirs() }
            val bmpFile = File(cacheDir, fileName)

            BmpEncoder.saveBmpToFile(design, bmpFormat, bmpFile)

            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                bmpFile
            )

            val specText = buildSpecText(design)
            shareUri(context, uri, "image/x-ms-bmp", specText, targetWhatsApp = true)
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "Error sharing BMP: ${e.message}", Toast.LENGTH_LONG).show()
        }
    }

    /**
     * Exports visual rendered image (PNG) and shares directly to WhatsApp
     */
    fun sharePictureToWhatsApp(context: Context, design: JacquardDesign, isWeaveSimulation: Boolean = false) {
        try {
            val bitmap = if (isWeaveSimulation) {
                JacquardEngine.renderWeaveSimulation(design)
            } else {
                JacquardEngine.renderColorBitmap(design)
            }

            val fileName = "${sanitizeFilename(design.title)}_preview.png"
            val cacheDir = File(context.cacheDir, "shared_files").apply { mkdirs() }
            val pngFile = File(cacheDir, fileName)

            FileOutputStream(pngFile).use { fos ->
                bitmap.compress(Bitmap.CompressFormat.PNG, 100, fos)
                fos.flush()
            }

            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                pngFile
            )

            val specText = buildSpecText(design)
            shareUri(context, uri, "image/png", specText, targetWhatsApp = true)
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "Error sharing picture: ${e.message}", Toast.LENGTH_LONG).show()
        }
    }

    /**
     * Saves raw BMP file to device Downloads folder
     */
    fun saveBmpToDevice(context: Context, design: JacquardDesign, bmpFormat: BmpFormat = design.config.bmpFormat): String? {
        return try {
            val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            if (!downloadsDir.exists()) downloadsDir.mkdirs()

            val fileName = "${sanitizeFilename(design.title)}_${design.widthHooks}x${design.heightPicks}_${System.currentTimeMillis() % 10000}.bmp"
            val targetFile = File(downloadsDir, fileName)

            BmpEncoder.saveBmpToFile(design, bmpFormat, targetFile)
            Toast.makeText(context, "Saved to Downloads: ${targetFile.name}", Toast.LENGTH_LONG).show()
            targetFile.absolutePath
        } catch (e: Exception) {
            // Fallback to app external files dir
            val fallbackDir = context.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS) ?: context.filesDir
            val fileName = "${sanitizeFilename(design.title)}_${design.widthHooks}x${design.heightPicks}.bmp"
            val targetFile = File(fallbackDir, fileName)
            BmpEncoder.saveBmpToFile(design, bmpFormat, targetFile)
            Toast.makeText(context, "Saved: ${targetFile.name}", Toast.LENGTH_LONG).show()
            targetFile.absolutePath
        }
    }

    private fun shareUri(context: Context, uri: Uri, mimeType: String, text: String, targetWhatsApp: Boolean) {
        val sendIntent = Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_TEXT, text)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }

        if (targetWhatsApp) {
            sendIntent.setPackage("com.whatsapp")
            try {
                context.startActivity(sendIntent)
                return
            } catch (e: Exception) {
                // WhatsApp not found, fallback to system chooser
                sendIntent.setPackage(null)
            }
        }

        val chooser = Intent.createChooser(sendIntent, "Share Jacquard Design / व्हाट्सएप शेयर")
        chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(chooser)
    }

    private fun sanitizeFilename(input: String): String {
        return input.replace(Regex("[^a-zA-Z0-9_-]"), "_").take(30)
    }
}
